#!/bin/bash

modprobe vfio-pci

for dev in "$@"; do
  vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
  device=$(cat /sys/bus/pci/devices/$dev/device)
  driver=$(readlink /sys/bus/pci/devices/$dev/driver)
  if [[ "$driver" != **/vfio-pci ]]; then
    if [ -n "$driver" ]; then
      echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
    fi
    echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id
  fi
done
