#!/bin/bash
# Windows virtual desktop

# Path to the script directory
SCRIPT_PATH=$(dirname $(realpath -s $0))

set -e

# Check if the system is using the NVIDIA GPU

if [ "$(prime-select query)" == nvidia ]; then
  echo "Sorry, but the NVIDIA GPU is in use."
  echo "Please, switch to the Intel GPU, restart your session and try again."
  exit
fi

if lsmod | cut -d' ' -f1 | grep -q nvidia; then
  set +e
  sudo rmmod nvidia &> /dev/null
  set -e
  if [ $? -ne 0 ]; then
    echo "Sorry, but the NVIDIA GPU is in use."
    echo "Please, switch to the Intel GPU, restart your session and try again."
    exit
  fi
fi

# Bind GPU, HDMI audio and an USB Controller

echo "Binding devices..."
sudo $SCRIPT_PATH/vfio-bind 0000:01:00.0 0000:01:00.1 0000:05:00.0
echo "done"

# Configure networks

if virsh net-list --inactive | grep -q isolated; then
  echo "Starting host-guest private network..."
  virsh net-start isolated
fi

# Launch Synergy if it is installed

if [ -x /usr/bin/synergys ]; then
  echo -n "Starting Synergy..."
  /usr/bin/synergys --daemon --restart --config "$SCRIPT_PATH/conf/synergy.conf"
  echo "done"
fi

echo "Starting virtual machine..."
virsh start hoth
