#!/bin/bash
# My Windows virtual desktop launch script

set -e

# Check if the system is using the NVIDIA GPU

if [ "$(prime-select query)" == nvidia ]; then
    echo "Sorry, but the NVIDIA GPU is in use."
    echo "Please, switch to the Intel GPU, restart your session and try again."
    exit
fi

# Here we go...

echo -n "Starting virtual machine... "
virsh start hoth

# Launch Synergy if it is installed

if [ -x /usr/bin/synergy ]; then
    if ! ps --no-headers -C synergy; then
        echo -n "Starting Synergy... "
        /usr/bin/synergy &> /dev/null &
        disown
        echo "Look at the system tray!"
    fi
fi
